### PR TITLE
added Dana Wanner

### PR DESCRIPTION
**Pull request by rennaw**

### CODE REVIEW

**Comment by mpmenne** [comment]
Hey Dana.   Thanks for the pull request!   Take a double look at your people.json....  It looks like it could be wiping out Robert Clark's merge.    Simple git pull should take care of it

**Comment by rennaw** [comment]
Oops sorry about that.  I do not mean to ask a dumb question but am I doing
the git pull on my file?

**Comment by mpmenne** [comment]
Try a git pull on the entire repo.

If that doesnt work Easiest way might be to do a fresh checkout and transfer the files.

Thanks Dana

**Comment by mpmenne** [comment]
Awesome!  thanks Dana!

**Comment by rennaw** [comment]
Hey Guys,

```
 Just checking in with you all to let you know that I am still very
```

interested in programming!

```
 Actually I have some exciting news...well I think it is exciting
```

anyway.  I decided to kind of chronicle my learning java through little
video tutorials.  I thought that by doing this not only would I re-enforce
what I have already learned, but maybe save others coming up a little
frustration and time by kinda following my path if you will.

```
 Anyway, I would appreciate it if you could take a look at a few of the
```

videos I made starting out and maybe give me some feedback.  If you think
they are good enough, I would love to see them at Launchcode TV.

```
 I was also wondering if this is something that would be worthwhile
```

putting out on our reddit page.  Please let me know your thoughts.  Oh and
the links to the videos are below.

https://www.youtube.com/watch?v=8jaoDQB-1xw
https://www.youtube.com/watch?v=_1zhvzIsiWM
https://www.youtube.com/watch?v=bzceHLZIkLU

Regards

Dana

**Comment by mpmenne** [comment]
Dana that is awesome!!!! I love it!  It's perfect.

**Comment by mpmenne** [comment]
These definitely belong on LaunchCodeTV.  I'll upload them tomorrow, or if you want to give it a shot, here's the video http://tv.launchcode.us/#/videos/uploading-to-launchcodetv?lesson=LaunchCode

Let me know if there's anything I can do to help

**Comment by rennaw** [comment]
Cool Mike!  I am glad you like them.  Go ahead and upload this time....I am
in the doghouse cause I was supposed to have had everything packed and
ready to go by now....and I am just starting the process.  (We are avid
campers!)

I will get more up to YouTube on Monday, and then will try my hand at
uploading those.

Have a good weekend!

Dana

**Comment by rennaw** [comment]
Hey Mike

I attempted to put up the 1st video.  Can you see what I did?  I am
struggling a bit because I cannot do this through the appliance....I have a
network adapter issue.
I troubleshoot PC issues for people from home and have a special network
adapter for that and then there is the virtual machine network adapter for
the appliance....I have to disable 1 to allow the other to run....

Long story short I am trying to use github via windows and Intellij and am
not sure if I am doing it correctly yet.  Could you please check and let me
know?

Thanks,

Dana

**Comment by mpmenne** [comment]
Yeah totally.  Let me take a look

**Comment by mpmenne** [comment]
Hey I was just thinking... Git in Windows using Intellij is probably a lot different than what you are used to.

One option is to install Cygwin on your windows machine.  It allows you to have a Linux command prompt in Windows.  When you go through the install / setup it lets you install actual linux libraries like git, node, etc.

Let me know your thoughts.
Mike

**Pull request merged**
