### PR TITLE
updated user Brian Giaraffa

### PR DESCRIPTION
**Pull request by b264**

### CODE REVIEW

**Comment by mpmenne** [comment]
Awesome.  Thanks Brian.  Good job getting to 8 man!

**Comment by mpmenne** [comment]
Once the automatic Travis CI build completes it will be live (only takes 4 minutes or so)
https://travis-ci.org/MoMenne/snap-scrip

Live site
http://cs50connection.com.s3-website-us-east-1.amazonaws.com/

**Comment by mpmenne** [comment]
err... wrong travis build.  https://travis-ci.org/MoMenne/cs50-connection

**Comment by b264** [comment]
Thanks for your time and all the helpful information you provide us.

**Pull request merged**
